#!/bin/bash
set -eu
test -z "${ERRAND_DEBUG:-<% if p('debug') %>1<% end %>}" || set -x
export ROOT=/var/vcap/jobs/tests/data/${1:-misc}

shield() {
  command shield --json "$@"
}

wait_for_task() {
  local task=$1
  echo "   - task $task"
  while true; do
    local status=$(shield task $task 2>/dev/null | jq -r '.status // "not-found"')
    case $status in
    (pending|running) sleep 0.1 ;;
    (""|scheduled)    sleep 1   ;;
    ("done")          echo "   - completed successfully (status=done)."
                      break     ;;
    (*)               echo "   - failure / anomaly detected (status=$status)."
                      command shield task $task
                      rc=1
                      break     ;;
    esac
  done
}

restore_latest() {
  local target=$1
  shield restore-archive "$(shield archives --target $target | jq -r '.[0].uuid')" | jq -r '.uuid'
}

check_encryption() {
    local target=$1
    local archive="$(shield archives --target $target | jq -r '.[0].key')"
    echo "Attempting to validate encryption for archive: $archive"
    aws s3api get-object --bucket $BUCKET --key $archive test_archive > /dev/null
    local rc=0
    if file --mime-type "test_archive" | grep -q bzip2$; then
        echo "!! Backup Archive is unencrypted - validate encryption process before release !!"
        echo
        rc=1
    else
        echo "Backup archive appears to be encrypted."
        echo
    fi
    rm -f test_archive
    return $rc
}