#!/bin/bash
source /var/vcap/jobs/tests/lib/functions etcd

#Adding keys and values for etcd with user auth
addKeyVals() {
    local url=$1
    local val1=$2
    local val2=$3
    local val3=$4
    echo "Putting three keys..."
    etcdctl --user root:tests --endpoints=$url put key1 $val1
    etcdctl --user root:tests --endpoints=$url put key2 $val2
    etcdctl --user root:tests --endpoints=$url put key3 $val3
}

#Adding keys and values for etcd-tls
addKeyValsTls() {
    local url=$1
    local val1=$2
    local val2=$3
    local val3=$4
    echo "Putting three keys..."
    etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url put key1 $val1
    etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url put key2 $val2
    etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url put key3 $val3
    echo
}

#Trashing data for etcd with user auth
trashVals() {
    local url=$1
    echo "Trashing data..."
    etcdctl --user root:tests --endpoints=$url put key1 valueChanged
    etcdctl --user root:tests --endpoints=$url del key2
    etcdctl --user root:tests --endpoints=$url put extraKey shouldNotExist
    echo
}

#Trasing data for etcd-tls
trashValsTls() {
    local url=$1
    echo "Trashing data..."
    etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url put key1 valueChanged
    etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url del key2
    etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url put extraKey shouldNotExist
    echo
}

#Getting values from keys for etcd with auth
verifyVals() {
    local url=$1
    local rc=0
    local val1=$2
    local val2=$3
    local val3=$4
    if [[ $(etcdctl --user root:tests --endpoints=$url get key1 --print-value-only) != "$val1" ]]; then
        echo "!! key1 was not initialized properly"
        rc=1
    else
        echo "Got correct value for key1 - $val1"
    fi

    if [[ $(etcdctl --user root:tests --endpoints=$url get key2 --print-value-only) != "$val2" ]]; then
        echo "!! key2 was not initialized properly"
        rc=1
    else
        echo "Got correct value for key2 - $val2"
    fi

    if [[ $(etcdctl --user root:tests --endpoints=$url get key3 --print-value-only) != "$val3" ]]; then
        echo "!! key3 was not initialized properly"
        rc=1
    else
        echo "Got correct value for key2 - $val3"
    fi

    if [[ $(etcdctl --user root:tests --endpoints=$url get extraKey --print-value-only) != "" ]]; then
        echo "!! Overwrite did not work correctly"
        rc=1
    else
        echo "Overwrite works. extraKey doesn't exist"
    fi

    echo
    return $rc
}

#Getting values from keys for etcd-tls
verifyValsTls() {
    local url=$1
    local rc=0
    local val1=$2
    local val2=$3
    local val3=$4
    if [[ $(etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url get key1 --print-value-only) != "$val1" ]]; then
        echo "!! key1 was not initialized properly"
        rc=1
    else
        echo "Got correct value for key1 - $val1"
    fi

    if [[ $(etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url get key2 --print-value-only) != "$val2" ]]; then
        echo "!! key2 was not initialized properly"
        rc=1
    else
        echo "Got correct value for key2 - $val2"
    fi

    if [[ $(etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url get key3 --print-value-only) != "$val3" ]]; then
        echo "!! key3 was not initialized properly"
        rc=1
    else
        echo "Got correct value for key2 - $val3"
    fi

    if [[ $(etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url get extraKey --print-value-only) != "" ]]; then
        echo "!! Overwrite did not work correctly"
        rc=1
    else
        echo "Overwrite works. extraKey doesn't exist"
    fi

    echo
    return $rc
}

#Prints all keys and values
dumpKeys() {
    local url=$1
    echo "Printing all keys and values"
    etcdctl --endpoints=$url --user root:tests get "" --prefix=true
    echo
}

#Prints all keys and values for etcd-tls
dumpKeysTls() {
    local url=$1
    echo "Printing all keys and values"
    etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url get "" --prefix=true
    echo
}

#Deletes all keys/values
deleteVals() {
    local url=$1
    echo "Deleting keys and values"
    etcdctl --endpoints=$url --user root:tests del "" --prefix=true
    echo
}

#Deletes all keys/values for etcd-tls
deleteValsTls() {
    local url=$1
    echo "Deleting keys and values"
    etcdctl --cacert=/var/vcap/jobs/tests/data/etcd-tls/tls/cert.pem --key=/var/vcap/data/targets/etcd/key.pem --cert=/var/vcap/data/targets/etcd/cert.pem --endpoints=$url del "" --prefix=true
    echo
}

runTests() {
    local target=$1
    local url=$2
    local rc=0

    export PATH=$PATH:/var/vcap/packages/etcd/bin/
    export ETCDCTL_API=3

    local val1=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    local val2=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    local val3=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

    echo -e ">> Setting up test data\n"
    if [ "$target" == "etcd-notls" ]; then
        deleteVals $url
        etcdctl --endpoints=$url user add root:tests || true
        etcdctl --endpoints=$url user grant-role root root || true
        etcdctl --endpoints=$url auth enable || true
        addKeyVals $url $val1 $val2 $val3
        dumpKeys $url
    else
        deleteValsTls $url
        addKeyValsTls $url $val1 $val2 $val3
        dumpKeysTls $url
    fi

    echo ">> running backup job"
    wait_for_task $(shield run-job ${target}-daily | jq -r '.task_uuid')
    echo

    echo -e ">> Messing up data\n"
    if [ "$target" == "etcd-notls" ]; then
        trashVals $url
        dumpKeys $url
    else
        trashValsTls $url
        dumpKeysTls $url
    fi
    echo

    if ! check_encryption ${target}; then
        rc=1
    fi

    echo ">> restoring from backups"
    wait_for_task $(restore_latest ${target})
    echo

    echo -e ">> Verifying test data\n"
    if [ "$target" == "etcd-notls" ]; then
        verifyVals $url $val1 $val2 $val3
        rc=$?
        dumpKeys $url
        etcdctl --endpoints=$url --user root:tests auth disable
        etcdctl --endpoints=$url user revoke-role root root
        etcdctl --endpoints=$url user delete root
        deleteVals $url
    else
        verifyValsTls $url $val1 $val2 $val3
        dumpKeysTls $url
        rc=$?
        deleteValsTls $url
    fi

    return $rc;
}

rc=0
cat <<EOF


###### ########  ###### ######
#         #     #       #     #
#         #    #        #      #
#####     #    #        #       #
#         #    #        #      #
#         #     #       #     #
######    #      ###### #####


EOF

echo ">> configuring SHIELD"
cat <<EOF | shield import -
core:  http://<%= link('shield').instances[0].address %>:8080
token: $SHIELD_AUTH_TOKEN

tenants:
  - name: Default Tenant

    systems:
      - name:   etcd-notls
        plugin: etcd
        agent:  $TARGET:5444
        config:
          endpoints:                http://$TARGET:2379
          fullOverwrite:            true
          auth:						true
          user:                     root
          pass:                     tests
        jobs:
          - name:    etcd-notls-daily
            when:    daily 1am
            retain:  2d
            storage: s3
            paused:  yes

      - name:   etcd-tls
        plugin: etcd
        agent:  $TARGET:5444
        config:
          endpoints:                https://$TARGET:2479
          fullOverwrite:            true
          auth:						true
          caCertPath:				/var/vcap/jobs/targets/config/etcd/tls/cert.pem
          clientCertPath:			/var/vcap/data/targets/etcd/cert.pem
          clientKeyPath:			/var/vcap/data/targets/etcd/key.pem
        jobs:
          - name:    etcd-tls-daily
            when:    daily 1am
            retain:  2d
            storage: s3
            paused:  yes
EOF

echo "Testing etcd without tls..."
runTests etcd-notls http://$TARGET:2379
rc=$?
echo

echo "Testing etcd with tls..."
runTests etcd-tls https://$TARGET:2479
rc=$(($rc + $?))

exit $rc