#!/bin/bash
source /var/vcap/jobs/run-tests/lib/functions mongodb

mongo() {
	command mongo --quiet mongodb://$TARGET "$@"
}

rc=0
cat <<EOF


##     ##  #######  ##    ##  ######    #######
###   ### ##     ## ###   ## ##    ##  ##     ##
#### #### ##     ## ####  ## ##        ##     ##
## ### ## ##     ## ## ## ## ##   #### ##     ##
##     ## ##     ## ##  #### ##    ##  ##     ##
##     ## ##     ## ##   ### ##    ##  ##     ##
##     ##  #######  ##    ##  ######    #######


EOF
echo "> MongoDB"
echo ">> setting up test data"
mongo $ROOT/init
mongo --eval 'db.collection.find({})' >$TMP/db.dat
echo "   initial contents of the database:"
sed -e 's/^/    /' <$TMP/db.dat
echo

echo ">> configuring SHIELD"
buckler create-target               \
  --name     mongodb-all            \
  --summary "MongoDB All Databases" \
  --plugin   mongo                  \
  --agent   "$TARGET:5444"

buckler create-job                    \
  --name       mongodb-all-daily      \
  --summary   "MongoDB All Databases" \
  --paused                            \
  --retention  short-term             \
  --schedule  "daily 3am"             \
  --store      s3                     \
  --target     mongodb-all
echo

echo ">> running backup job"
wait_for_task $(buckler run mongodb-all-daily | jq -r '.task_uuid')
echo

echo ">> trashing the data"
echo "   deleting all of the data out of 'db'"
mongo --eval 'db.collection.deleteMany({})'
echo "   contents of the database are now:"
mongo --eval 'db.collection.find({})' | sed -e 's/^/    /'
echo

echo ">> restoring from backups"
wait_for_task $(buckler restore $(buckler archives -t mongodb-all | jq -r '.[0].uuid') | jq -r '.task_uuid')
echo

echo ">> verifying data, post-restore"
echo "   contents of 'db':"
mongo --eval 'db.collection.find({})' | sed -e 's/^/    /'

mongo --eval 'db.collection.find({})' >$TMP/db.post

if ! diff -u $TMP/db.dat $TMP/db.post &>/dev/null; then
	echo "!! db was not properly restored!"
	echo
	diff -u $TMP/db.dat $TMP/db.post || true
	echo
	rc=1
fi

exit $rc
