#!/usr/bin/bash
set -eu
# vim:ft=bash

JOB=$1
TARGET=$2

export JOB_DIR=/var/vcap/jobs/$JOB
export RUN_DIR=/var/vcap/sys/run/$JOB
export LOG_DIR=/var/vcap/sys/log/$JOB
export TMP_DIR=/var/vcap/sys/tmp/$JOB
export STORE_DIR=/var/vcap/store/$JOB
chmod 755 $JOB_DIR

for dir in $RUN_DIR $LOG_DIR $TMP_DIR $STORE_DIR; do
  mkdir -p ${dir}
  chown vcap:vcap ${dir}
  chmod 775 ${dir}
done

if [[ -d /var/vcap/packages/$TARGET/bin ]]; then
  export PATH=$PATH:/var/vcap/packages/$TARGET/bin
fi

exec >>$LOG_DIR/$TARGET.log 2>&1
export HOME=${HOME:-/home/vcap}
export TMPDIR=$TMP_DIR

PIDFILE=$RUN_DIR/$TARGET.pid

pid_guard() {
  local file=$1
  local name=$2

  if [[ -f "$file" ]]; then
    local pid=$(head -1 "$file")
    if [[ -n "$pid" && -e /proc/$pid ]]; then
      echo "$name is already running, please stop it first"
      exit 1
    fi
    rm $file
  fi
}

kill_and_wait() {
  local file=$1
  if [[ -f "$file" ]]; then
    local pid=$(head -1 "$file")
    if [[ -z "$pid" ]]; then
      exit 1
    fi
    n=250
    if [[ -e /proc/$pid ]]; then
      kill $pid
      while [[ -e /proc/$pid ]]; do
        sleep 0.1
        if [[ $n -eq 0 ]]; then
          kill -9 $pid
          sleep 0.5
          break
        fi
        n=$(( $n - 1 ))
      done
    else
      kill $pid
    fi
    rm -f $file
  fi
}
