#!/bin/bash
set -eu

fail() {
  echo >&2 $*
  exit 1
}
latest_uploaded_stemcell() {
  echo $(bosh stemcells | grep bosh | grep ubuntu | awk -F'|' '{ print $2, $3 }' | sort -nr -k2 | head -n1 | awk '{ print $1 }')
}


BOSH_STATUS=$(bosh status)
DIRECTOR_UUID=$(echo "$BOSH_STATUS" | grep UUID | awk '{print $2}')
DIRECTOR_CPI=$(echo "$BOSH_STATUS" | grep CPI | awk '{print $2}' | sed -e 's/_cpi//')
DIRECTOR_NAME=$(echo "$BOSH_STATUS" | grep Name | sed 's/.*Name *//')

if [[ $DIRECTOR_CPI != "warden" ]]; then
  fail "Not targeting bosh-lite with warden CPI. Please make sure you have run 'bosh target' and are targeting a BOSH lite before running this script."
fi
if ! command -v spruce >/dev/null 2>&1; then
  fail "spruce is not installed. Please download at https://github.com/geofffranks/spruce/releases"
fi

STEMCELL=${STEMCELL:-$(latest_uploaded_stemcell)}
if [[ -z ${STEMCELL} ]]; then
  STEMCELL_URL=https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent
  echo
  echo "Uploading latest $DIRECTOR_CPI/$STEMCELL_OS stemcell..."
  echo " (from ${STEMCELL_URL})"
  bosh upload stemcell $STEMCELL_URL
fi
STEMCELL=${STEMCELL:-$(latest_uploaded_stemcell)}

TPL=$(dirname $0)
TMP=$(cd $TPL/..; pwd)/tmp
mkdir -p $TMP
export DIRECTOR_UUID STEMCELL
spruce merge --prune meta $TPL/shield.yml > $TMP/manifest.yml
bosh deployment $TMP/manifest.yml
bosh status
