#!/bin/bash
#
# ci/run
#
# CI/CD component for deploying Phalanx with a new candidard
# SHIELD distribution, and running errands against it.
#
# author:  James Hunt <james@niftylogic.com>
# created: 2017-02-04
#

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

header "Setting up ~/.bosh_config..."
cat > ~/.bosh_config << EOF
---
aliases:
  target:
    bosh-lite: ${BOSH_LITE_TARGET}
auth:
  ${BOSH_LITE_TARGET}:
    username: ${BOSH_LITE_USERNAME}
    password: ${BOSH_LITE_PASSWORD}
EOF

VERSION=$(cat $VERSION/version)

set -e
pushd ${SHIELD} &>/dev/null
header "Creating a new SHIELD distribution, v${VERSION}..."

ROOT=$(pwd)
GOPATH=${ROOT%%/gopath/*}/gopath
PATH="${PATH}:${GOPATH}/bin"
echo "  (Using GOPATH ${GOPATH})"
go get github.com/mitchellh/gox
make release
popd &>/dev/null

cp ${SHIELD}/artifacts/shield-server-linux-amd64.tar.gz \
   ${PHALANX}/src/shield-rc/shield-server-linux-amd64.tar.gz

pushd ${PHALANX} &>/dev/null
header "Deploying Phalanx for SHIELD v${VERSION}..."

export BOSH_ENVIRONMENT=${BOSH_LITE_TARGET}
export BOSH_CLIENT=${BOSH_LITE_USERNAME}
export BOSH_CLIENT_SECRET=${BOSH_LITE_PASSWORD}
export BOSH_DEPLOYMENT=${BOSH_LITE_DEPLOYMENT}

header "Cleaning up from any previous deployments..."
bosh delete-deployment -n || echo "continuing on..."

header "Creating candidate BOSH release..."
bosh2 create-release --force
bosh2 upload-release || echo "continuing on..."

header "Deploying to BOSH-lite..."
cat <<EOF | spruce merge ci/manifest.yml - > .ci.yml
meta:
  aws:
    access_key: (( grab \$AWS_ACCESS_KEY ))
    secret_key: (( grab \$AWS_SECRET_KEY ))
EOF
bosh2 -n deploy .ci.yml
rm -f .ci.yml

header "Running the Phalanx test errand..."
bosh2 run-errand tests

header "Cleaning up..."
bosh delete-deployment -n || echo "continuing on..."
bosh clean-up -n || echo "continuing on..."
popd &>/dev/null

echo
echo "SUCCESS"
exit 0
